x= {"_text":"",
    "index_unit": "M",
    "sections": {
                "Version": [HeaderItem(mnemonic="VERS", unit="", value="3.0", descr="CWLS LOG ASCII STANDA"),
                            HeaderItem(mnemonic="WRAP", unit="", value="NO", descr="ONE LINE PER DEPTH STE"),
                            HeaderItem(mnemonic="DLM", unit="", value="SPACE", descr="DELIMITING CHARACTER")],
                "Well": [   HeaderItem(mnemonic="STRT", unit="m", value="0", descr="First reference value"),
                            HeaderItem(mnemonic="STOP", unit="m", value="3709.8", descr="Last reference va"),
                            HeaderItem(mnemonic="STEP", unit="m", value="0.2", descr="Step increment"),
                            HeaderItem(mnemonic="NULL", unit="", value="-9999", descr="Missing value"),
                            HeaderItem(mnemonic="COMP", unit="", value="PurOilGas(PNG)", descr="Company"),
                            HeaderItem(mnemonic="WELL", unit="", value="148R", descr="Well name"),
                            HeaderItem(mnemonic="FLD", unit="", value="Кулгинское", descr="Field"),
                            HeaderItem(mnemonic="LOC", unit="", value="", descr="Location"),
                            HeaderItem(mnemonic="SRVC", unit="", value="", descr="Service Company"),
                            HeaderItem(mnemonic="CTRY", unit="", value="Ро", descr="Country"),
                            HeaderItem(mnemonic="DATE", unit="", value="16/09/2018", descr="Service Date"),
                            HeaderItem(mnemonic="X", unit="m", value="358990.07", descr="X or East-West co"),
                            HeaderItem(mnemonic="Y", unit="m", value="6355497.6", descr="Y or North South "),
                            HeaderItem(mnemonic="GDAT", unit="", value="", descr="Geodetic Datum"),
                            HeaderItem(mnemonic="HZCS", unit="", value="", descr="Horizontal Co-ordinate S"),
                            HeaderItem(mnemonic="API", unit="", value="", descr="API NUMBER"),
                            HeaderItem(mnemonic="CNTY", unit="", value="WEST_SIBERIA", descr=""),
                            HeaderItem(mnemonic="COUNTRY", unit="", value="Россия", descr="Страна"),
                            HeaderItem(mnemonic="EREF", unit="m", value="149.63", descr=""),
                            HeaderItem(mnemonic="FL", unit="", value="ЯНАО", descr="Регион"),
                            HeaderItem(mnemonic="HOLE", unit="", value="", descr="Номер ствола"),
                            HeaderItem(mnemonic="KUST", unit="", value="", descr="Куст"),
                            HeaderItem(mnemonic="ORIGINALWELLNAME", unit="", value="KUK_148R", descr=""),
                            HeaderItem(mnemonic="PROV", unit="", value="", descr="PROVINCE"),
                            HeaderItem(mnemonic="STAT", unit="", value="RUSSIA", descr=""),
                            HeaderItem(mnemonic="TD", unit="m", value="10.0", descr=""),
                            HeaderItem(mnemonic="UWI", unit="", value="", descr=""),
                            HeaderItem(mnemonic="GROUP", unit="", value="Кулгинская", descr="")],
                "Curves": [ CurveItem(mnemonic="DEPT", unit="m", value="", descr="DEPTH {F}", original_mnemonic="DEPT", data.shape=(18550)),
                            CurveItem(mnemonic="AZIMUT", unit="deg", value="", descr="Azimut {F}", original_mnemonic="AZIMUT", data.shape=(18550)), CurveItem(mnemonic="BIOT", unit="_", value="", descr="Biot {F}", original_mnemonic="BIOT", data.shape=(18550)),
                            CurveItem(mnemonic="CMW_KICK", unit="ppg", value="", descr="Kick Pressure (Mud Weight Equivalent) {F}", original_mnemonic="CMW_KICK", data.shape=(18550)),
                            CurveItem(mnemonic="CMW_KICK_2", unit="ppg", value="", descr="Kick Pressure (Mud Weight Equivalent) {F}", original_mnemonic="CMW_KICK_2", data.shape=(18550)),
                            CurveItem(mnemonic="CMW_LOSS", unit="ppg", value="", descr="Mud Loss (Mud Weight Equivalent) {F}", original_mnemonic="CMW_LOSS", data.shape=(18550)),
                            CurveItem(mnemonic="CMW_LOSS_2", unit="ppg", value="", descr="Mud Loss (Mud Weight Equivalent) {F}", original_mnemonic="CMW_LOSS_2", data.shape=(18550)),
                            CurveItem(mnemonic="CMW_MAX_MTS", unit="ppg", value="", descr="Breakdown Pressure (Mud Weight Equivalent) {F}", original_mnemonic="CMW_MAX_MTS", data.shape=(18550)),
                            CurveItem(mnemonic="CMW_MAX_MTS_2", unit="ppg", value="", descr="Breakdown Pressure (Mud Weight Equivalent) {F}", original_mnemonic="CMW_MAX_MTS_2", data.shape=(18550)),
                            CurveItem(mnemonic="CMW_MIN_MC", unit="ppg", value="", descr="Shear Failure Min Pressure (Mud Weight Equivalent) {F}", original_mnemonic="CMW_MIN_MC", data.shape=(18550)),
                            CurveItem(mnemonic="CMW_MIN_MC_2", unit="ppg", value="", descr="Shear Failure Min Pressure (Mud Weight Equivalent) {F}", original_mnemonic="CMW_MIN_MC_2", data.shape=(18550)),
                            CurveItem(mnemonic="CO_BEFORE_CALIBRATION", unit="MPa", value="", descr="Co_before_calibration {F}", original_mnemonic="CO_BEFORE_CALIBRATION", data.shape=(18550)),
                            CurveItem(mnemonic="E", unit="GPa", value="", descr="E {F}", original_mnemonic="E", data.shape=(18550)),
                            CurveItem(mnemonic="MAX_MW", unit="ppg", value="", descr="Max Mud Weight {F}", original_mnemonic="MAX_MW", data.shape=(18550)),
                            CurveItem(mnemonic="MI_DEG", unit="deg", value="", descr="mi_deg {F}", original_mnemonic="MI_DEG", data.shape=(18550)),
                            CurveItem(mnemonic="MIN_MW", unit="ppg", value="", descr="Min Mud Weight {F}", original_mnemonic="MIN_MW", data.shape=(18550)),
                            CurveItem(mnemonic="MUD_DENSITY", unit="kg/m3", value="", descr="Mud_density {F}", original_mnemonic="MUD_DENSITY", data.shape=(18550)),
                            CurveItem(mnemonic="POISON", unit="_", value="", descr="Poison {F}", original_mnemonic="POISON", data.shape=(18550)),
                            CurveItem(mnemonic="PP", unit="MPa", value="", descr="Pp {F}", original_mnemonic="PP", data.shape=(18550)),
                            CurveItem(mnemonic="SH_MAX_V", unit="MPa", value="", descr="SH_max_v {F}", original_mnemonic="SH_MAX_V", data.shape=(18550)),
                            CurveItem(mnemonic="SH_MIN_V", unit="MPa", value="", descr="Sh_min_v {F}", original_mnemonic="SH_MIN_V", data.shape=(18550)),
                            CurveItem(mnemonic="STRESS_AZIMUT_TYPE3", unit="deg", value="", descr="{F}", original_mnemonic="STRESS_AZIMUT_TYPE3", data.shape=(18550)),
                            CurveItem(mnemonic="SV", unit="MPa", value="", descr="Sv {F}", original_mnemonic="SV", data.shape=(18550)),
                            CurveItem(mnemonic="TENSILE_STRENGTH", unit="MPa", value="", descr="Tensile_strength {F}", original_mnemonic="TENSILE_STRENGTH", data.shape=(18550)),
                            CurveItem(mnemonic="ZENIT", unit="deg", value="", descr="Zenit {F}", original_mnemonic="ZENIT", data.shape=(18550))],
                "Parameter": [HeaderItem(mnemonic="SET", unit="", value="Кулгинская_148R", descr=""),
                            HeaderItem(mnemonic="TLFAMILY_AZIMUT", unit="", value="", descr=""),
                            HeaderItem(mnemonic="TLFAMILY_BIOT", unit="", value="Biot Coefficient", descr=""),
                            HeaderItem(mnemonic="TLFAMILY_CMW_KICK", unit="", value="Kick Pressure (Mud We"),
                            HeaderItem(mnemonic="TLFAMILY_CMW_KICK_2", unit="", value="Kick Pressure (Mud "),
                            HeaderItem(mnemonic="TLFAMILY_CMW_LOSS", unit="", value="Mud Loss (Mud Weight "),
                            HeaderItem(mnemonic="TLFAMILY_CMW_LOSS_2", unit="", value="Mud Loss (Mud Weigh"),
                            HeaderItem(mnemonic="TLFAMILY_CMW_MAX_MTS", unit="", value="Breakdown Pressure"),
                            HeaderItem(mnemonic="TLFAMILY_CMW_MAX_MTS_2", unit="", value="Breakdown Pressu"),
                            HeaderItem(mnemonic="TLFAMILY_CMW_MIN_MC", unit="", value="Shear Failure Min P"),
                            HeaderItem(mnemonic="TLFAMILY_CMW_MIN_MC_2", unit="", value="Shear Failure Min"),
                            HeaderItem(mnemonic="TLFAMILY_CO_BEFORE_CALIBRATION", unit="", value="Unconfin"),
                            HeaderItem(mnemonic="TLFAMILY_DEPT", unit="", value="Measured Depth", descr=""),
                            HeaderItem(mnemonic="TLFAMILY_E", unit="", value="Youngs Modulus (Dynamic)", descr=""),
                            HeaderItem(mnemonic="TLFAMILY_MAX_MW", unit="", value="Mud Weight", descr=""),
                            HeaderItem(mnemonic="TLFAMILY_MIN_MW", unit="", value="Mud Weight", descr=""),
                            HeaderItem(mnemonic="TLFAMILY_MUD_DENSITY", unit="", value="Mud Weight", descr=""),
                            HeaderItem(mnemonic="TLFAMILY_POISON", unit="", value="Poisson Ratio (Static)"),
                            HeaderItem(mnemonic="TLFAMILY_PP", unit="", value="Pore Pressure", descr=""),
                            HeaderItem(mnemonic="TLFAMILY_SH_MAX_V", unit="", value="Hydrocarbon Saturatio"),
                            HeaderItem(mnemonic="TLFAMILY_SH_MIN_V", unit="", value="Hydrocarbon Saturatio"),
                            HeaderItem(mnemonic="TLFAMILY_STRESS_AZIMUT_TYPE3", unit="", value="Stress Azi"),
                            HeaderItem(mnemonic="TLFAMILY_SV", unit="", value="Vertical Stress", descr=""),
                            HeaderItem(mnemonic="TLFAMILY_TENSILE_STRENGTH", unit="", value="Tension", des=""),
                            HeaderItem(mnemonic="TLFAMILY_ZENIT", unit="", value="Angle", descr=""),
                            HeaderItem(mnemonic="TLFAMILY_MI_DEG", unit="", value="Friction Angle", descr="" )],
                "Other": ""},
    "encoding": "UTF-8"}
