x= {"_text":"",
    "index_unit": "M",
    "sections": {
                "Version": [HeaderItem(mnemonic="VERS", unit="", value="3.0", descr="CWLS LOG ASCII STANDA"),
                            HeaderItem(mnemonic="WRAP", unit="", value="NO", descr="ONE LINE PER DEPTH STE"),
                            HeaderItem(mnemonic="DLM", unit="", value="SPACE", descr="DELIMITING CHARACTER")],
                "Well": [   HeaderItem(mnemonic="STRT", unit="m", value="0", descr="First reference value"),
                            HeaderItem(mnemonic="STOP", unit="m", value="3709.8", descr="Last reference va"),
                            HeaderItem(mnemonic="STEP", unit="m", value="0.2", descr="Step increment"),
                            HeaderItem(mnemonic="NULL", unit="", value="-9999", descr="Missing value"),
                            HeaderItem(mnemonic="COMP", unit="", value="PurOilGas(PNG)", descr="Company"),
                            HeaderItem(mnemonic="WELL", unit="", value="148R", descr="Well name"),
                            HeaderItem(mnemonic="FLD", unit="", value="Кулгинское", descr="Field"),
                            HeaderItem(mnemonic="LOC", unit="", value="", descr="Location"),
                            HeaderItem(mnemonic="SRVC", unit="", value="", descr="Service Company"),
                            HeaderItem(mnemonic="CTRY", unit="", value="Ро", descr="Country"),
                            HeaderItem(mnemonic="DATE", unit="", value="16/09/2018", descr="Service Date"),
                            HeaderItem(mnemonic="X", unit="m", value="358990.07", descr="X or East-West co"),
                            HeaderItem(mnemonic="Y", unit="m", value="6355497.6", descr="Y or North South "),
                            HeaderItem(mnemonic="GDAT", unit="", value="", descr="Geodetic Datum"),
                            HeaderItem(mnemonic="HZCS", unit="", value="", descr="Horizontal Co-ordinate S"),
                            HeaderItem(mnemonic="API", unit="", value="", descr="API NUMBER"),
                            HeaderItem(mnemonic="CNTY", unit="{'DEPT': {'unit': 'm', 'dots': array([0.0000e+00, 2.0000e-01, 4.0000e-01, ..., 3.7094e+03, 3.7096e+03,\n" +
                                "       3.7098e+03])}, 'AZIMUT': {'unit': 'deg', 'dots': array([         nan, 228.66999817, 228.66999817, ..., 131.53895569,\n" +
                                "       131.53895569, 131.53895569])}, 'BIOT': {'unit': '_', 'dots': array([       nan, 0.85000002, 0.85000002, ..., 0.85000002, 0.85000002,\n" +
                                "       0.85000002])}, 'CMW_KICK': {'unit': 'ppg', 'dots': array([     nan,      nan,      nan, ..., 8.590127, 8.590126, 8.590128])}, 'CMW_KICK_2': {'unit': 'ppg', 'dots': array([     nan,      nan,      nan, ..., 8.590127, 8.590126, 8.590128])}, 'CMW_LOSS': {'unit': 'ppg', 'dots': array([     nan,      nan,      nan, ..., 15.03191, 14.98891, 15.46326])}, 'CMW_LOSS_2': {'unit': 'ppg', 'dots': array([     nan,      nan,      nan, ..., 15.03191, 14.98891, 15.46326])}, 'CMW_MAX_MTS': {'unit': 'ppg', 'dots': array([     nan,      nan,      nan, ..., 24.78345, 24.85734, 25.62764])}, 'CMW_MAX_MTS_2': {'unit': 'ppg', 'dots': array([     nan,      nan,      nan, ..., 24.78345, 24.85734, 25.62764])}, 'CMW_MIN_MC': {'unit': 'ppg', 'dots': array([     nan,      nan,      nan, ..., 6.513881, 6.234836, 6.686839])}, 'CMW_MIN_MC_2': {'unit': 'ppg', 'dots': array([     nan,      nan,      nan, ..., 6.513881, 6.234836, 6.686839])}, 'CO_BEFORE_CALIBRATION': {'unit': 'MPa', 'dots': array([        nan,         nan,         nan, ..., 86.60386658,\n" +
                                "       93.45007324, 85.80859375])}, 'E': {'unit': 'GPa', 'dots': array([        nan,         nan,         nan, ..., 59.31054306,\n" +
                                "       63.31977081, 64.29989624])}, 'MAX_MW': {'unit': 'ppg', 'dots': array([     nan, 9.999965, 9.999965, ..., 9.999965, 9.999965, 9.999965])}, 'MI_DEG': {'unit': 'deg', 'dots': array([        nan,         nan,         nan, ..., 41.98721313,\n" +
                                "       41.98721313, 41.98721313])}, 'MIN_MW': {'unit': 'ppg', 'dots': array([     nan, 9.68067 , 9.68067 , ..., 8.762675, 8.762675, 8.762675])}, 'MUD_DENSITY': {'unit': 'kg/m3', 'dots': array([  nan, 1160., 1160., ..., 1050., 1050., 1050.])}, 'POISON': {'unit': '_', 'dots': array([       nan,        nan,        nan, ..., 0.3140932 , 0.30788505,\n" +
                                "       0.32270744])}, 'PP': {'unit': 'MPa', 'dots': array([           nan, 2.02085890e-03, 4.04171740e-03, ...,\n" +
                                "       3.67449722e+01, 3.67469940e+01, 3.67490158e+01])}, 'SH_MAX_V': {'unit': 'MPa', 'dots': array([        nan,         nan,         nan, ..., 64.30024719,\n" +
                                "       64.11980438, 66.15263367])}, 'SH_MIN_V': {'unit': 'MPa', 'dots': array([        nan,         nan,         nan, ..., 64.30024719,\n" +
                                "       64.11980438, 66.15263367])}, 'STRESS_AZIMUT_TYPE3': {'unit': 'deg', 'dots': array([150., 150., 150., ..., 150., 150., 150.])}, 'SV': {'unit': 'MPa', 'dots': array([        nan,         nan,         nan, ..., 84.23340607,\n" +
                                "       84.23910523, 84.24479675])}, 'TENSILE_STRENGTH': {'unit': 'MPa', 'dots': array([       nan,        nan,        nan, ..., 8.66038704, 9.34500694,\n" +
                                "       8.58085918])}, 'ZENIT': {'unit': 'deg', 'dots': array([       nan, 0.        , 0.        , ..., 1.53947294, 1.53947294,\n" +
                                "       1.53947294])}}\n", value="WEST_SIBERIA", descr=""),
                            HeaderItem(mnemonic="COUNTRY", unit="", value="Россия", descr="Страна"),
                            HeaderItem(mnemonic="EREF", unit="m", value="149.63", descr=""),
                            HeaderItem(mnemonic="FL", unit="", value="ЯНАО", descr="Регион"),
                            HeaderItem(mnemonic="HOLE", unit="", value="", descr="Номер ствола"),
                            HeaderItem(mnemonic="KUST", unit="", value="", descr="Куст"),
                            HeaderItem(mnemonic="ORIGINALWELLNAME", unit="", value="KUK_148R", descr=""),
                            HeaderItem(mnemonic="PROV", unit="", value="", descr="PROVINCE"),
                            HeaderItem(mnemonic="STAT", unit="", value="RUSSIA", descr=""),
                            HeaderItem(mnemonic="TD", unit="m", value="10.0", descr=""),
                            HeaderItem(mnemonic="UWI", unit="", value="", descr=""),
                            HeaderItem(mnemonic="GROUP", unit="", value="Кулгинская", descr="")],
                "Curves": [ CurveItem(mnemonic="DEPT", unit="m", value="", descr="DEPTH {F}", original_mnemonic="DEPT", data.shape=(18550)),
                            CurveItem(mnemonic="AZIMUT", unit="deg", value="", descr="Azimut {F}", original_mnemonic="AZIMUT", data.shape=(18550)), CurveItem(mnemonic="BIOT", unit="_", value="", descr="Biot {F}", original_mnemonic="BIOT", data.shape=(18550)),
                            CurveItem(mnemonic="CMW_KICK", unit="ppg", value="", descr="Kick Pressure (Mud Weight Equivalent) {F}", original_mnemonic="CMW_KICK", data.shape=(18550)),
                            CurveItem(mnemonic="CMW_KICK_2", unit="ppg", value="", descr="Kick Pressure (Mud Weight Equivalent) {F}", original_mnemonic="CMW_KICK_2", data.shape=(18550)),
                            CurveItem(mnemonic="CMW_LOSS", unit="ppg", value="", descr="Mud Loss (Mud Weight Equivalent) {F}", original_mnemonic="CMW_LOSS", data.shape=(18550)),
                            CurveItem(mnemonic="CMW_LOSS_2", unit="ppg", value="", descr="Mud Loss (Mud Weight Equivalent) {F}", original_mnemonic="CMW_LOSS_2", data.shape=(18550)),
                            CurveItem(mnemonic="CMW_MAX_MTS", unit="ppg", value="", descr="Breakdown Pressure (Mud Weight Equivalent) {F}", original_mnemonic="CMW_MAX_MTS", data.shape=(18550)),
                            CurveItem(mnemonic="CMW_MAX_MTS_2", unit="ppg", value="", descr="Breakdown Pressure (Mud Weight Equivalent) {F}", original_mnemonic="CMW_MAX_MTS_2", data.shape=(18550)),
                            CurveItem(mnemonic="CMW_MIN_MC", unit="ppg", value="", descr="Shear Failure Min Pressure (Mud Weight Equivalent) {F}", original_mnemonic="CMW_MIN_MC", data.shape=(18550)),
                            CurveItem(mnemonic="CMW_MIN_MC_2", unit="ppg", value="", descr="Shear Failure Min Pressure (Mud Weight Equivalent) {F}", original_mnemonic="CMW_MIN_MC_2", data.shape=(18550)),
                            CurveItem(mnemonic="CO_BEFORE_CALIBRATION", unit="MPa", value="", descr="Co_before_calibration {F}", original_mnemonic="CO_BEFORE_CALIBRATION", data.shape=(18550)),
                            CurveItem(mnemonic="E", unit="GPa", value="", descr="E {F}", original_mnemonic="E", data.shape=(18550)),
                            CurveItem(mnemonic="MAX_MW", unit="ppg", value="", descr="Max Mud Weight {F}", original_mnemonic="MAX_MW", data.shape=(18550)),
                            CurveItem(mnemonic="MI_DEG", unit="deg", value="", descr="mi_deg {F}", original_mnemonic="MI_DEG", data.shape=(18550)),
                            CurveItem(mnemonic="MIN_MW", unit="ppg", value="", descr="Min Mud Weight {F}", original_mnemonic="MIN_MW", data.shape=(18550)),
                            CurveItem(mnemonic="MUD_DENSITY", unit="kg/m3", value="", descr="Mud_density {F}", original_mnemonic="MUD_DENSITY", data.shape=(18550)),
                            CurveItem(mnemonic="POISON", unit="_", value="", descr="Poison {F}", original_mnemonic="POISON", data.shape=(18550)),
                            CurveItem(mnemonic="PP", unit="MPa", value="", descr="Pp {F}", original_mnemonic="PP", data.shape=(18550)),
                            CurveItem(mnemonic="SH_MAX_V", unit="MPa", value="", descr="SH_max_v {F}", original_mnemonic="SH_MAX_V", data.shape=(18550)),
                            CurveItem(mnemonic="SH_MIN_V", unit="MPa", value="", descr="Sh_min_v {F}", original_mnemonic="SH_MIN_V", data.shape=(18550)),
                            CurveItem(mnemonic="STRESS_AZIMUT_TYPE3", unit="deg", value="", descr="{F}", original_mnemonic="STRESS_AZIMUT_TYPE3", data.shape=(18550)),
                            CurveItem(mnemonic="SV", unit="MPa", value="", descr="Sv {F}", original_mnemonic="SV", data.shape=(18550)),
                            CurveItem(mnemonic="TENSILE_STRENGTH", unit="MPa", value="", descr="Tensile_strength {F}", original_mnemonic="TENSILE_STRENGTH", data.shape=(18550)),
                            CurveItem(mnemonic="ZENIT", unit="deg", value="", descr="Zenit {F}", original_mnemonic="ZENIT", data.shape=(18550))],
                "Parameter": [HeaderItem(mnemonic="SET", unit="", value="Кулгинская_148R", descr=""),
                            HeaderItem(mnemonic="TLFAMILY_AZIMUT", unit="", value="", descr=""),
                            HeaderItem(mnemonic="TLFAMILY_BIOT", unit="", value="Biot Coefficient", descr=""),
                            HeaderItem(mnemonic="TLFAMILY_CMW_KICK", unit="", value="Kick Pressure (Mud We"),
                            HeaderItem(mnemonic="TLFAMILY_CMW_KICK_2", unit="", value="Kick Pressure (Mud "),
                            HeaderItem(mnemonic="TLFAMILY_CMW_LOSS", unit="", value="Mud Loss (Mud Weight "),
                            HeaderItem(mnemonic="TLFAMILY_CMW_LOSS_2", unit="", value="Mud Loss (Mud Weigh"),
                            HeaderItem(mnemonic="TLFAMILY_CMW_MAX_MTS", unit="", value="Breakdown Pressure"),
                            HeaderItem(mnemonic="TLFAMILY_CMW_MAX_MTS_2", unit="", value="Breakdown Pressu"),
                            HeaderItem(mnemonic="TLFAMILY_CMW_MIN_MC", unit="", value="Shear Failure Min P"),
                            HeaderItem(mnemonic="TLFAMILY_CMW_MIN_MC_2", unit="", value="Shear Failure Min"),
                            HeaderItem(mnemonic="TLFAMILY_CO_BEFORE_CALIBRATION", unit="", value="Unconfin"),
                            HeaderItem(mnemonic="TLFAMILY_DEPT", unit="", value="Measured Depth", descr=""),
                            HeaderItem(mnemonic="TLFAMILY_E", unit="", value="Youngs Modulus (Dynamic)", descr=""),
                            HeaderItem(mnemonic="TLFAMILY_MAX_MW", unit="", value="Mud Weight", descr=""),
                            HeaderItem(mnemonic="TLFAMILY_MIN_MW", unit="", value="Mud Weight", descr=""),
                            HeaderItem(mnemonic="TLFAMILY_MUD_DENSITY", unit="", value="Mud Weight", descr=""),
                            HeaderItem(mnemonic="TLFAMILY_POISON", unit="", value="Poisson Ratio (Static)"),
                            HeaderItem(mnemonic="TLFAMILY_PP", unit="", value="Pore Pressure", descr=""),
                            HeaderItem(mnemonic="TLFAMILY_SH_MAX_V", unit="", value="Hydrocarbon Saturatio"),
                            HeaderItem(mnemonic="TLFAMILY_SH_MIN_V", unit="", value="Hydrocarbon Saturatio"),
                            HeaderItem(mnemonic="TLFAMILY_STRESS_AZIMUT_TYPE3", unit="", value="Stress Azi"),
                            HeaderItem(mnemonic="TLFAMILY_SV", unit="", value="Vertical Stress", descr=""),
                            HeaderItem(mnemonic="TLFAMILY_TENSILE_STRENGTH", unit="", value="Tension", des=""),
                            HeaderItem(mnemonic="TLFAMILY_ZENIT", unit="", value="Angle", descr=""),
                            HeaderItem(mnemonic="TLFAMILY_MI_DEG", unit="", value="Friction Angle", descr="" )],
                "Other": ""},
    "encoding": "UTF-8"}
